---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: natrouter-archlinux
    image: base/archlinux
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        natrouter_ignore_docker: no
  lint:
    name: ansible-lint
scenario:
  name: archlinux
verifier:
  name: goss
  lint:
    name: yamllint
