---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux" tag="1"
    - image="amazonlinux"
    - image="alpine"
    - image="alpine" tag="edge"
    # - namespace="archlinux" image="base"
    - image="debian" tag="unstable"
    - image="debian"
    - image="fedora"
    - image="fedora" tag="rawhide"
    - image="opensuse"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="alpine" tag="edge"
    - env: image="debian" tag="unstable"
    - env: image="fedora" tag="rawhide"
    - env: image="ubuntu" tag="rolling"
    - env: image="ubuntu" tag="devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "nhkHSTLIvqLxa0u0R1pn7spsXWsLWjSFkWBM0vt8nI8tT0TnJd/TRCvWk8GhERop6nOOlZ9sh8XRmKy42sXTq7Cxi+XuSPqDv+80KQNWK48aLhq1daKzwTPFjxAy91RUSLg1QmwEhcrXpKwZ7ndWmnyXN4nt9PB7BS9+Nku30HaB3o7NOUYhJkzQBBvqg06SwGRx8Q0zo5aXy7kc7FFpA9FqMsuEFUviKDOVfhHw+8q/uSZx8KNFbAs3QRZIEMDb7O5DXRbLAnIAwxqnFYXn5am1nqX+EoEDTaD8H5QbgQ9p+rsALLMlBZcUd60Ary2JazuG3lTFUwvi4Mx1QRDNafE0d9CM2q22bvQ3fn5ESQwdkpu4p5rBHGSietQX+ANy07OU//buEVdFPchQcC17AvsA/WpPWVnvpmW8FBq+cBL1AEt6+YejxYZM+FDgbWytrER2LoPwMK8qUlq5MXAZ+Q5HHf23Ix9GqJH9VQXH7F9uobXSP5fcAxULzeweWoYuwIkLvPtIFlS9DOVNs0mHHoJN64Gg+scegavW38R2iuxiADLlMt6xbFovAGViaGuUg8Xekgvx/4UGjLqfM9UqxQzK5evXs2e3gc5KuN4Js0Z+8IceeIWieZstpViuUa+1//7HufnE1qp+KE1l0NJrT7vKKWKzkzeAk1I2pTbcwhs="
  email: false
