---

- name: test if natrouter_public_interface is set correctly
  assert:
    that:
      - natrouter_public_interface is defined
    quiet: yes

- name: test if natrouter_private_network is set correctly
  assert:
    that:
      - natrouter_private_network is defined
    quiet: yes

- name: test if natrouter_destination is set correctly
  assert:
    that:
      - natrouter_destination is defined
    quiet: yes

- name: test if natrouter_protocols is set correctly
  assert:
    that:
      - natrouter_protocols is defined
      - natrouter_protocols is iterable
    quiet: yes

- name: test if item in natrouter_protocols is set correctly
  assert:
    that:
      - item is defined
      - item in [ "dccp", "tcp", "sctp", "udp" ]
    quiet: yes
  loop: "{{ natrouter_protocols }}"
