---
# tasks file for natrouter
- name: install iptables
  package:
    name: iptables
    state: present
  register: iptables_install_iptables
  until: iptables_install_iptables
  retries: 3

- name: enable ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    state: present
    value: 1
    reload: yes
  when:
    - ansible_virtualization_type != "docker"

- name: set routing rules
  iptables:
    table: nat
    state: present
    chain: POSTROUTING
    out_interface: "{{ natrouter_public_interface }}"
    source: "{{ natrouter_private_network }}"
    destination: "{{ natrouter_destination }}"
    jump: MASQUERADE
    protocol: "{{ item }}"
    comment: Ansible NAT Masquerade
  with_items:
    - "{{ natrouter_protocols }}"
  when:
    - ansible_virtualization_type != "docker"
