---
# tasks file for ansible-role-natrouter
- name: enable ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: True

- name: set routing rules
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: '{{ public_interface }}'
    source: '{{ private_network }}'
    destination: '{{ destination }}'
    jump: MASQUERADE
    protocol: '{{ item }}'
    comment: Ansible NAT Masquerade
  with_items:
    - "{{ protocols }}"
