---
# tasks file for natrouter
- name: install iptables
  package:
    name: iptables
    state: present
  register: iptables_install_iptables
  until: iptables_install_iptables is succeeded
  retries: 3

- name: set routing rules
  iptables:
    table: nat
    state: present
    chain: POSTROUTING
    out_interface: "{{ natrouter_public_interface }}"
    source: "{{ natrouter_private_network }}"
    destination: "{{ natrouter_destination }}"
    jump: MASQUERADE
    protocol: "{{ item }}"
    comment: Ansible NAT Masquerade
  loop: "{{ natrouter_protocols }}"
  when:
    - ansible_connection != "docker"
