---
- name: Prepare
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.sysctl
      sysctl_items:
        name: net.ipv4.ip_forward
        value: 1
